version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - datavolume:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PASS: password
      DB_PORT: 5432
      DB_USER: postgres
    ports:
      - 8080:8080
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      SERVER: backend
    depends_on:
      - "backend"
    ports:
      - 80:80
volumes:
  datavolume: