version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - datavolume:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  datavolume: