name: Build Frontend
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: cd frontend && npm install
            - run: cd frontend && npm run generate
            - uses: vimtor/action-zip@v1
              with:
                files: frontend/dist/
                dest: frontend/dist.zip
            - uses: actions/upload-artifact@v2
              with:
                name: dist
                path: frontend/dist.zip
    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v2
              with:
                name: dist
            - run: mv dist.zip frontend/
            - run: cd frontend && unzip dist.zip -d dist
            - run: cd frontend && docker build -t frontend .
            - run: docker tag frontend registry.digitalocean.com/todos/frontend:$GITHUB_SHA
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl registry login
            - run: docker push registry.digitalocean.com/todos/frontend:$GITHUB_SHA